### ISSUE TITLE
Cannot delete student

### ISSUE THREAD

**Issue by PyroJayxX** [chaotic-braindead/Enrollment#5]
Tried deleting a student in the admin dashboard => **student masterlist** but results with sql error

![image](https://github.com/chaotic-braindead/Enrollment/assets/113975518/35a9e3ae-0837-49b4-b3f7-9cd545eaddc1)

**Comment by chaotic-braindead** [comment]
Your database copy is outdated. Please use the newer version of the db. Thanks
