### ISSUE TITLE
Admin Dashboard Class List Table

### ISSUE THREAD

**Issue by PyroJayxX** [chaotic-braindead/Enrollment#7]
![image](https://github.com/chaotic-braindead/Enrollment/assets/113975518/09a11dd8-db3b-4784-a712-2f1a2a2f8509)

In the Admin Dashboard => **Records** => **Class List**
When coming from an empty table, when you load another table, the table gets bugged out.

**Example:** Instances where the **year** combobox (middle cmb) is 1, 4, or 5 are empty datasets 

When you load those empty dataset instances, then load another table with existing dataset, 
the table bugs out as seen in the above pic

**Comment by chaotic-braindead** [comment]
Found a fix [here.](https://stackoverflow.com/questions/25000659/javafx-bug-tableview-is-not-rendering-correctly-some-rows) Should be good by next commit.

**Comment by chaotic-braindead** [comment]
adding `tbl.refresh()` after each TableView generation seems to have fixed the issue.
