### ISSUE TITLE
Admin Dashboard College Maintenance Table-View

### ISSUE THREAD

**Issue by PyroJayxX** [chaotic-braindead/Enrollment#8]
![image](https://github.com/chaotic-braindead/Enrollment/assets/113975518/631f0bcf-10ad-440a-a833-5411eb8ad606)

### Table-view is always bugged upon arrival when you come from other views/panes.

When clicking **Maintenance** => **College** in the NavBar, the College table bugs out as seen in the img above

But when you re-click the **College** from the **NavBar** (while still inside _college_ view), the table-view works as intended,

**Comment by chaotic-braindead** [comment]
Found a fix [here.](https://stackoverflow.com/questions/25000659/javafx-bug-tableview-is-not-rendering-correctly-some-rows) Should be good by next commit.
