### ISSUE TITLE
Admin Dashboard Block Scheduling 

### ISSUE THREAD

**Issue by PyroJayxX** [chaotic-braindead/Enrollment#9]
![image](https://github.com/chaotic-braindead/Enrollment/assets/113975518/f95e676b-3354-4c00-90e1-1ef921757cf2)

In the Admin Dashboard Block Scheduling View

Upon **clicking a row** in the table, the following error occurs: _'Invalid day of the week_'; and the input for the _day_ checkbox **disappears**.

Additionally, the value of the _block_ combobox is **set** to the subject description of **whichever row** you selected in the table-view.

**Comment by chaotic-braindead** [comment]
The app you're running might be from an older commit. I have already fixed this issue yesterday.
![image](https://github.com/chaotic-braindead/Enrollment/assets/102578910/696b4d9f-93ba-4c80-920f-33023b11f3a2)
